### ISSUE TITLE
The plugin stop working 

### ISSUE THREAD

**Issue by ViktorStevich** [fomkin/adt-maven-plugin#26]
Hi all, 

By April 18, 2017, Symantec will decommission the "Legacy" timestamping service.

(Legacy) RFC 3161 SHA128 Timestamp Service: 
https://timestamp.geotrust.com/tsa

To support business continuity for our customers, we have provided the following replacement services.

(New) RFC 3161 Service SHA256: 
http://sha256timestamp.ws.symantec.com/sha256/timestamp

In order for me to use it I will need to poin to the new location, otherwise the builds are failing.

Cheers,

Viktor

**Comment by ViktorStevich** [comment]
That link: https://timestamp.geotrust.com/tsa is probably set in adt.project and has nothing to do with your project. Marked as resolved

**Comment by rdawe** [comment]
I believe this needs support for the -tsa option on the packager (I don't see it now)

This would allow us to either set it to the new value (http://sha256timestamp.ws.symantec.com/sha256/timestamp) or "none"

**Comment by ViktorStevich** [comment]
exactly, we needs something like: 

  <plugin>
                <groupId>com.yelbota.plugins</groupId>
                <artifactId>adt-maven-plugin</artifactId>
                <version>1.0.9.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>package</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <tsa> THIS ONE </tsa>
                    <sdkVersion>3.9</sdkVersion>
                    <target>bundle</target>

**Comment by lukasishouty** [comment]
It is possible to pass parameter to command goal instead of using the package goal. But it is very fiddly and as Viktor mentioned above, the configuration is better option.
`<execution>
  <id>adtCommand</id>
  <goals>
    <goal>command</goal>
  </goals>
  <configuration>
    <arguments>-package -tsa none -storetype pkcs12 -keystore ${basedir}\yourcertificate.p12 otherArgumentsAndParametersLikeCompilationFilesAndAssets</arguments>
  </configuration>
</execution>`
